import React from 'react';
import { useHistoryStore } from '../stores/historyStore';
import type { SmartCollection } from '../types';
import { evaluateSmartCollection } from '../hooks/useHistoryFilters';
import { 
  X, BookOpen, Sparkles, Folder, Trash2, 
  Clock, Award, Zap, FolderHeart
} from 'lucide-react';

interface CollectionsSidebarProps {
  onClose: () => void;
}

export const CollectionsSidebar: React.FC<CollectionsSidebarProps> = ({ onClose }) => {
  const {
    entries,
    collections,
    activeSmartCollectionId,
    setActiveSmartCollectionId,
    deleteCollection
  } = useHistoryStore();

  // Smart collections specification
  const SMART_COLLECTIONS: Array<SmartCollection & { icon: React.ReactNode; color: string }> = [
    { 
      id: 'smart_top_10', 
      title: 'Top 10 Renders', 
      query: 'top_10', 
      autoGenerated: true,
      icon: <Clock size={12} />,
      color: '#3b82f6' // Blue
    },
    { 
      id: 'smart_high_res', 
      title: 'Highly Res Renders', 
      query: 'high_res', 
      autoGenerated: true,
      icon: <Zap size={12} />,
      color: '#eab308' // Yellow
    },
    { 
      id: 'smart_reused', 
      title: 'Reused Prompts', 
      query: 'reused', 
      autoGenerated: true,
      icon: <Award size={12} />,
      color: '#10b981' // Green
    },
    { 
      id: 'smart_architectural', 
      title: 'Architectural Favorites', 
      query: 'architectural', 
      autoGenerated: true,
      icon: <FolderHeart size={12} />,
      color: '#ec4899' // Pink
    },
  ];

  const handleSelectCollection = (id: string | null) => {
    setActiveSmartCollectionId(id);
  };

  return (
    <div className="pinboard-sidebar">
      <div className="pinboard-header">
        <BookOpen size={14} color="#e11d48" />
        <span>Collections Workspace</span>
        <button 
          className="modal-close" 
          onClick={onClose} 
          style={{ position: 'static', width: 26, height: 26, marginLeft: 'auto' }}
        >
          <X size={13} />
        </button>
      </div>

      <div className="pinboard-list">
        {/* All Collections Filter */}
        <button
          className={`pinboard-item ${activeSmartCollectionId === null ? 'pinboard-item-active' : ''}`}
          onClick={() => handleSelectCollection(null)}
        >
          <span className="col-dot" style={{ background: '#666' }} />
          <span>All Renders</span>
        </button>

        {/* Smart auto-generated Collections */}
        <div className="sidebar-section-title">
          <Sparkles size={11} className="section-title-icon" />
          <span>SMART COLLECTIONS</span>
        </div>

        {SMART_COLLECTIONS.map(smartCol => {
          const count = evaluateSmartCollection(smartCol.id, entries).length;
          const isActive = activeSmartCollectionId === smartCol.id;

          return (
            <button
              key={smartCol.id}
              className={`pinboard-item smart-item ${isActive ? 'pinboard-item-active' : ''}`}
              onClick={() => handleSelectCollection(smartCol.id)}
            >
              <span className="col-icon" style={{ color: smartCol.color }}>
                {smartCol.icon}
              </span>
              <span className="pinboard-item-name">{smartCol.title}</span>
              <span className="pinboard-item-count">{count}</span>
            </button>
          );
        })}

        {/* User manual Collections */}
        <div className="sidebar-section-title">
          <Folder size={11} className="section-title-icon" />
          <span>MY COLLECTIONS</span>
        </div>

        {collections.map(col => {
          const isActive = activeSmartCollectionId === col.id;

          return (
            <div 
              key={col.id} 
              className={`pinboard-item-wrap ${isActive ? 'pinboard-item-active' : ''}`}
            >
              <button 
                className="pinboard-item" 
                onClick={() => handleSelectCollection(col.id)}
              >
                <span className="col-dot" style={{ background: col.color }} />
                <span className="pinboard-item-name">{col.name}</span>
                <span className="pinboard-item-count">{col.entryIds.length}</span>
              </button>
              
              <button 
                className="pinboard-delete" 
                onClick={() => deleteCollection(col.id)} 
                title="Delete collection"
              >
                <Trash2 size={11} />
              </button>
            </div>
          );
        })}

        {collections.length === 0 && (
          <div className="col-empty" style={{ padding: '16px 12px', fontSize: '11px', color: '#666' }}>
            No custom collections yet. Add images using the bookmark icon on card overlays.
          </div>
        )}
      </div>
    </div>
  );
};
