import React from 'react';

import type { HistoryEntry, HistoryGroup } from '../types';
import { useLazyImage } from '../hooks/useLazyImage';
import { useHistoryStore } from '@/stores/historyStore';
import { 
  CheckSquare, Square, Star, FolderOpen, Eye, 
  Trash2, BookmarkPlus, ChevronsLeftRight, Timer,
  Image as ImageIcon, Sparkles
} from 'lucide-react';
import { formatDuration, getDateLabel } from '@/services/history/HistoryService';

interface HistoryCardProps {
  entry?: HistoryEntry;
  group?: HistoryGroup;
  isGroup?: boolean;
  onStar: (e: React.MouseEvent, id: string) => void;
  onDelete: (e: React.MouseEvent, id: string) => void;
  onAddToCollection: (e: React.MouseEvent, id: string) => void;
  onOpenWorkflow: (entry: HistoryEntry) => void;
}

export const HistoryCard: React.FC<HistoryCardProps> = ({
  entry,
  group,
  isGroup = false,
  onStar,
  onDelete,
  onAddToCollection,
  onOpenWorkflow
}) => {
  const {
    selectMode,
    selectedIds,
    toggleSelectId,
    setPreviewEntry,
    setActiveGroup,
    collections
  } = useHistoryStore();

  const targetId = isGroup ? group!.sourceImageId : entry!.id;
  const { containerRef, src: imageSrc, isLoading, error } = useLazyImage(targetId, isGroup ? 'root_source' : 'output');
  
  const isSelected = isGroup
    ? Array.from(selectedIds).some(id => group!.children.some(c => c.id === id))
    : selectedIds.has(entry!.id);
    
  const isStarred = isGroup
    ? group!.children.some(c => c.starred)
    : entry!.starred || false;

  const isInAnyCollection = React.useMemo(() => {
    if (isGroup) {
      return group!.children.some(c => collections.some(col => col.entryIds.includes(c.id)));
    }
    return collections.some(col => col.entryIds.includes(entry!.id));
  }, [collections, isGroup, entry, group]);

  // Check if this image/group was analyzed or generated by Anarchy Generation
  const isAnarchyGeneration = React.useMemo(() => {
    if (isGroup) {
      return group!.children.some(c => 
        c.model?.toLowerCase().includes('anarchy') || 
        c.type?.toLowerCase().includes('anarchy') || 
        c.tags?.some(t => t.toLowerCase().includes('anarchy'))
      );
    }
    const m = entry?.model?.toLowerCase() || '';
    const t = entry?.type?.toLowerCase() || '';
    const tagsStr = entry?.tags?.join(' ').toLowerCase() || '';
    return m.includes('anarchy') || t.includes('anarchy') || tagsStr.includes('anarchy') || entry?.prompt?.toLowerCase().includes('anarchy');
  }, [isGroup, group, entry]);

  const handleCardClick = () => {
    if (selectMode) {
      if (isGroup) {
        const groupIds = group!.children.map(c => c.id);
        const allSelected = groupIds.every(id => selectedIds.has(id));
        groupIds.forEach(id => {
          if (allSelected && selectedIds.has(id)) {
            toggleSelectId(id);
          } else if (!allSelected && !selectedIds.has(id)) {
            toggleSelectId(id);
          }
        });
      } else {
        toggleSelectId(entry!.id);
      }
    } else {
      if (isGroup) {
        setActiveGroup(group!);
      } else {
        setPreviewEntry(entry!);
      }
    }
  };

  if (isGroup) {
    const mainEntry = group!.children[0] || entry;
    const variantsCount = group!.children.length;

    return (
      <div
        ref={containerRef}
        className={`history-grid-item group-card ${isLoading ? 'skeleton-card' : ''} ${isSelected ? 'selected' : ''}`}
        onClick={handleCardClick}
      >
        {isLoading ? (
          <>
            <div className="grid-image-container skeleton-image">
              <div className="skeleton-shimmer" />
            </div>
            <div className="grid-item-info">
              <div className="skeleton-line sk-prompt" />
              <div className="skeleton-meta-row">
                <div className="skeleton-line sk-model" />
                <div className="skeleton-line sk-date" />
              </div>
            </div>
          </>
        ) : (
          <>
            <div className="grid-image-container group-image-stack">
              {error || !imageSrc ? (
                <div className="grid-img-error">
                  <ImageIcon size={22} style={{ opacity: 0.25, color: '#ffffff' }} />
                </div>
              ) : (
                <img src={imageSrc} alt={group!.sourceImageLabel} className="grid-img-out" loading="lazy" />
              )}
              
              <div className="group-badge">
                <span>{variantsCount} variants</span>
              </div>

              {isAnarchyGeneration && (
                <div className="anarchy-gen-badge" title="Analyzed & Generated by Anarchy Generation">
                  <Sparkles size={9} className="anarchy-gen-icon" />
                  <span>Anarchy Gen</span>
                </div>
              )}

              {selectMode && (
                <div className="item-select-check">
                  {isSelected ? <CheckSquare size={14} color="#e11d48" /> : <Square size={14} />}
                </div>
              )}
            </div>

            <div className="grid-item-info">
              <span className="grid-item-prompt">{group!.sourceImageLabel || mainEntry?.prompt || 'Grouped Workflow'}</span>
              <div className="grid-item-meta">
                <span className="grid-item-model">
                  {mainEntry?.model ? mainEntry.model.split(' ').slice(0, 2).join(' ') : 'Workflow'}
                </span>
                <span className="grid-item-date">{getDateLabel(group!.timestamp)}</span>
              </div>
            </div>
          </>
        )}
      </div>
    );
  }

  const hasBothImages = Boolean(entry!.sourceImageKey && entry!.outputImageKey);

  return (
    <div
      ref={containerRef}
      className={`history-grid-item ${isLoading ? 'skeleton-card' : ''} ${isStarred ? 'starred' : ''} ${isSelected ? 'selected' : ''}`}
      onClick={handleCardClick}
    >
      {isLoading ? (
        <>
          <div className="grid-image-container skeleton-image">
            <div className="skeleton-shimmer" />
          </div>
          <div className="grid-item-info">
            <div className="skeleton-line sk-prompt" />
            <div className="skeleton-meta-row">
              <div className="skeleton-line sk-model" />
              <div className="skeleton-line sk-date" />
            </div>
          </div>
        </>
      ) : (
        <>
          <div className="grid-image-container single-image">
            {error || !imageSrc ? (
              <div className="grid-img-error">
                <ImageIcon size={22} style={{ opacity: 0.25, color: '#ffffff' }} />
              </div>
            ) : (
              <img src={imageSrc} alt={entry!.label} className="grid-img-out" loading="lazy" />
            )}

            {isAnarchyGeneration && (
              <div className="anarchy-gen-badge" title="Analyzed & Generated by Anarchy Generation">
                <Sparkles size={9} className="anarchy-gen-icon" />
                <span>Anarchy Gen</span>
              </div>
            )}

            {selectMode && (
              <div className="item-select-check">
                {selectedIds.has(entry!.id) ? <CheckSquare size={14} color="#e11d48" /> : <Square size={14} />}
              </div>
            )}

            {hasBothImages && !selectMode && (
              <div className="split-badge">
                <ChevronsLeftRight size={8} strokeWidth={2.5} />
                <span>B/A</span>
              </div>
            )}

            {isInAnyCollection && !selectMode && (
              <div className="collection-badge"><BookmarkPlus size={9} /></div>
            )}

            {!selectMode && (
              <div className="grid-item-actions" onClick={e => e.stopPropagation()}>
                <button className="grid-action-btn" onClick={(e) => { e.stopPropagation(); onOpenWorkflow(entry!); }} title="Use (Workflow)"><FolderOpen size={11} /></button>
                <button className="grid-action-btn" onClick={(e) => { e.stopPropagation(); setPreviewEntry(entry!); }} title="View Details"><Eye size={11} /></button>
                <button className={`grid-action-btn ${isStarred ? 'star-active' : ''}`} onClick={(e) => onStar(e, entry!.id)} title={isStarred ? 'Unstar' : 'Star'}><Star size={11} fill={isStarred ? '#e11d48' : 'none'} /></button>
                <button className={`grid-action-btn ${isInAnyCollection ? 'star-active' : ''}`} onClick={(e) => onAddToCollection(e, entry!.id)} title="Add to Collection"><BookmarkPlus size={11} /></button>
                <button className="grid-action-btn" onClick={(e) => onDelete(e, entry!.id)} title="Delete"><Trash2 size={11} /></button>
              </div>
            )}
          </div>

          <div className="grid-item-info">
            <span className="grid-item-prompt">{entry!.prompt || entry!.label}</span>
            <div className="grid-item-meta">
              <span className="grid-item-model">
                {entry!.model ? entry!.model.split(' ').slice(0, 2).join(' ') : entry!.type}
              </span>
              <div className="grid-item-right-meta">
                {entry!.duration && entry!.duration > 0 && (
                  <span className="grid-item-duration">
                    <Timer size={8.5} />
                    {formatDuration(entry!.duration)}
                  </span>
                )}
                <span className="grid-item-date">{getDateLabel(entry!.timestamp)}</span>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
};
