import type { ReactNode } from 'react';
import { OperationType, NodeRole, NodeState } from './classification';

export interface HistoryEntry {
  id: string;
  timestamp: number;
  type: OperationType;
  label: string;
  prompt?: string;
  project?: string;
  model?: string;
  inputImage?: string;
  outputImage?: string;
  rootSourceImage?: string;
  duration?: number;
  starred?: boolean;
  params?: Record<string, any>;
  nodeTree?: NodeTreeData;
  rootSourceId?: string;
  parentId?: string;
  rootId?: string;
  maskImageKey?: string;
  maskImageUrl?: string;
  unscaledRegion?: { x: number; y: number; width: number; height: number };
  /**
   * @deprecated Mostly redundant with `type` (OperationType).
   */
  nodeType?: NodeRole | 'canvas';
}

export interface NodeTreeData {
  nodes: Array<{
    id: string;
    type: NodeRole;
    position: { x: number; y: number };
    image?: string;
    prompt?: string;
    processingType?: OperationType;
    state?: NodeState;
    children?: string[];
    parentId?: string;
    historyEntryId?: string;
  }>;
  sourceNodeId: string;
  activeNodeId?: string;
  createdAt: number;
}

export interface HistoryGroup {
  id: string;
  sourceImageId: string;
  sourceImage: string;
  createdAt: number;
  children: HistoryEntry[];
  totalGenerations: number;
  totalUpscales: number;
  totalVariations: number;
  lastModified: number;
}

export interface SmartCollection {
  id: string;
  title: string;
  query: string;
  autoGenerated: boolean;
  icon?: ReactNode;
}

export type FilterType = 'all' | 'render' | 'upscale' | 'variation' | 'edit' | 'generate' | 'starred' | 'pinboard';

export interface HistoryStats {
  total: number;
  starred: number;
  totalDuration: number;
  types: Record<string, number>;
  todayCount: number;
}

export interface SemanticProgress {
  status: string;
  name?: string;
  file?: string;
  progress?: number;
  loaded?: number;
  total?: number;
}
