import type { ReactNode } from 'react';

export interface HistoryEntry {
  id: string;
  timestamp: number;
  type: 'render' | 'upscale' | 'variation' | 'edit' | 'generate';
  label: string;
  prompt?: string;
  project?: string;
  model?: string;
  inputImage?: string;       // Holds object URL pointing to Blob at runtime
  outputImage?: string;      // Holds object URL pointing to Blob at runtime
  rootSourceImage?: string;  // Holds object URL pointing to Blob at runtime
  duration?: number;         // Execution duration in ms
  starred?: boolean;
  params?: Record<string, any>;
  nodeTree?: NodeTreeData;
  rootSourceId?: string;
}

export interface NodeTreeData {
  nodes: Array<{
    id: string;
    type: 'source' | 'ghost' | 'result';
    position: { x: number; y: number };
    image?: string;
    prompt?: string;
    processingType?: string;
    state?: 'idle' | 'processing' | 'ready' | 'completed' | 'error';
    children?: string[];
    parentId?: string;
  }>;
  sourceNodeId: string;
  createdAt: number;
}

export interface HistoryGroup {
  id: string;             // Typically matching rootSourceId
  sourceImageId: string;
  sourceImage: string;    // Object URL of the root source image
  createdAt: number;
  children: HistoryEntry[];
  totalGenerations: number;
  totalUpscales: number;
  totalVariations: number;
  lastModified: number;
}

export interface SmartCollection {
  id: string;
  title: string;
  query: string; // Dynamic query descriptor or matching logic function key
  autoGenerated: boolean;
  icon?: ReactNode;
}

export type FilterType = 'all' | 'render' | 'upscale' | 'variation' | 'edit' | 'generate' | 'starred' | 'pinboard';
