import type { ReplicateModel, ModelMeta } from './replicateTypes';

export const MODEL_META: Record<ReplicateModel, ModelMeta> = {
  // ── 1. Nano Banana 2 (Gemini 3.1 Flash Image) ──────────────────────────────
  'google/nano-banana-2': {
    supportsImg2Img: true,
    supportsMultiImage: true,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 14,
    resolutions: ['1K', '2K', '4K'],
    aspectRatios: ['1:1', '2:3', '3:2', '3:4', '4:3', '4:5', '5:4', '9:16', '16:9', '21:9'],
    pricePerImage: 0.067,
  },
  'google/nano-banana-2-lite': {
    supportsImg2Img: true,
    supportsMultiImage: true,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 14,
    resolutions: ['1K'],
    aspectRatios: ['1:1', '2:3', '3:2', '3:4', '4:3', '4:5', '5:4', '9:16', '16:9', '21:9'],
    pricePerImage: 0.034,
  },
  // ── 2.1. Seedream 5 Pro ─────────────────────────────────────────────────────
  'bytedance/seedream-5-pro': {
    supportsImg2Img: true,
    supportsMultiImage: true,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 14,
    resolutions: ['1K', '2K'],
    aspectRatios: ['match_input_image', '1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3', '21:9'],
    pricePerImage: 0.045,
  },
  // ── 3. FLUX 2 Pro ────────────────────────────────────────────────────────────
  'black-forest-labs/flux-2-pro': {
    supportsImg2Img: true,
    supportsMultiImage: true,
    supportsSeed: true,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: true,
    defaultSteps: 28,
    stepsRange: [1, 50],
    maxReferenceImages: 8,
    resolutions: ['0.5K', '1K', '2K', '4K'],
    aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3'],
    pricePerImage: 0.015,
  },
  // ── 4. GPT Image 2 ──────────────────────────────────────────────────────────
  'openai/gpt-image-2': {
    supportsImg2Img: true,
    supportsMultiImage: true,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 10,
    resolutions: ['auto', 'low', 'medium', 'high'],
    aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', 'auto'],
    pricePerImage: 0.128,
  },
  // ── 4.1. GPT Image 2.5 Flare ───────────────────────────────────────────────
  'openai/gpt-image-2.5-flare': {
    supportsImg2Img: true,
    supportsMultiImage: true,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 10,
    resolutions: ['auto', 'low', 'medium', 'high', 'xhigh', 'max'],
    aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', 'auto'],
    pricePerImage: 0.25,
  },
  // ── 4.2. GPT Image 2.5 Sunburst ────────────────────────────────────────────
  'openai/gpt-image-2.5-sunburst': {
    supportsImg2Img: true,
    supportsMultiImage: true,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 10,
    resolutions: ['auto', 'low', 'medium', 'high', 'xhigh', 'max'],
    aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', 'auto'],
    pricePerImage: 0.25,
  },
  // ── 5. Nano Banana Pro (Gemini 3 Pro Image) ──────────────────────────────────
  'google/nano-banana-pro': {
    supportsImg2Img: true,
    supportsMultiImage: true,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 14,
    resolutions: ['1K', '2K', '4K'],
    aspectRatios: ['1:1', '2:3', '3:2', '3:4', '4:3', '4:5', '5:4', '9:16', '16:9', '21:9'],
    pricePerImage: 0.15,
  },

  // ── Pruna AI P-Image ────────────────────────────────────────────────────────
  'prunaai/p-image': {
    supportsImg2Img: true,
    supportsMultiImage: false,
    supportsSeed: true,
    supportsSteps: true,
    supportsNegativePrompt: true,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 25,
    stepsRange: [1, 50],
    maxReferenceImages: 1,
    resolutions: ['1K', '2K'],
    aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3'],
    pricePerImage: 0.005,
  },
  // ── Krea 2 Large ────────────────────────────────────────────────────────────
  'krea/krea-2-large': {
    supportsImg2Img: true,
    supportsMultiImage: false,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 30,
    stepsRange: [1, 50],
    maxReferenceImages: 1,
    resolutions: ['Auto'],
    aspectRatios: ['1:1', '4:3', '3:2', '16:9', '2.35:1', '4:5', '2:3', '3:4', '9:16'],
    pricePerImage: 0.06,
  },
  // ── 9. Stable Diffusion 3.5 Large ────────────────────────────────────────
  'stability-ai/stable-diffusion-3.5-large': {
    supportsImg2Img: true,
    supportsMultiImage: false,
    supportsSeed: true,
    supportsSteps: true,
    supportsNegativePrompt: true,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: true,
    defaultSteps: 28,
    stepsRange: [20, 50],
    maxReferenceImages: 1,
    resolutions: ['Auto'],
    aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '21:9', '9:21'],
    pricePerImage: 0.065, // $0.065 per image (official Replicate price)
  },

  // ── Reve AI Models ──────────────────────────────────────────────────────────
  'reve/edit-fast': {
    supportsImg2Img: true,
    supportsMultiImage: true,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 8,
    resolutions: ['Auto'],
    aspectRatios: ['1:1', '16:9', '9:16', '3:2', '2:3', '4:3', '3:4', '21:9', '9:21', 'auto'],
    pricePerImage: 0.01,
  },
  'reve/create': {
    supportsImg2Img: true,
    supportsMultiImage: true,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 8,
    resolutions: ['Auto'],
    aspectRatios: ['1:1', '16:9', '9:16', '3:2', '2:3', '4:3', '3:4', '21:9', '9:21', 'auto'],
    pricePerImage: 0.01,
  },
  'reve/extract-layout': {
    supportsImg2Img: true,
    supportsMultiImage: false,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 1,
    resolutions: ['Auto'],
    aspectRatios: ['auto'],
    pricePerImage: 0.01,
  },
  'reve/render-layout': {
    supportsImg2Img: true,
    supportsMultiImage: true,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 8,
    resolutions: ['Auto'],
    aspectRatios: ['auto'],
    pricePerImage: 0.01,
  },
  'reve/create-layout': {
    supportsImg2Img: false,
    supportsMultiImage: false,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 0,
    resolutions: ['Auto'],
    aspectRatios: ['auto'],
    pricePerImage: 0.01,
  },
  'reve/reconcile-layouts': {
    supportsImg2Img: false,
    supportsMultiImage: false,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 0,
    resolutions: ['Auto'],
    aspectRatios: ['auto'],
    pricePerImage: 0.01,
  },

  // ── 10. Topaz Labs Image Upscale ──────────────────────────────────────────
  'topazlabs/image-upscale': {
    supportsImg2Img: false,
    supportsMultiImage: false,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: true,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 0,
    resolutions: ['2x', '4x', '6x'],
    aspectRatios: [],
    pricePerImage: 0.05,
  },
  // ── 11. Pruna AI P-Image Upscale ───────────────────────────────────────────
  'prunaai/p-image-upscale': {
    supportsImg2Img: false,
    supportsMultiImage: false,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: true,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 0,
    resolutions: ['1x', '2x', '4x', '8x', '16x'],
    aspectRatios: [],
    pricePerImage: 0.01,
  },

  // ── 12. Clarity Upscaler ─────────────────────────────────────────────────
  'philz1337x/clarity-upscaler': {
    supportsImg2Img: false,
    supportsMultiImage: false,
    supportsSeed: true,
    supportsSteps: true,
    supportsNegativePrompt: true,
    supportsUpscale: true,
    supportsLoRA: true,
    supportsReferenceStrength: false,
    defaultSteps: 20,
    stepsRange: [1, 100],
    maxReferenceImages: 0,
    resolutions: ['1x', '2x', '4x'],
    aspectRatios: [],
    pricePerImage: 0.01,
  },
  // ── 12.1. Anarchy Upscale (Clarity Pro) ──────────────────────────────────
  'philz1337x/clarity-pro-upscaler': {
    supportsImg2Img: false,
    supportsMultiImage: false,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: true,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 0,
    resolutions: ['2x', '4x', '8x', '16x'],
    aspectRatios: [],
    pricePerImage: 0.03,
  },
  // ── 13. Wan 2.1 i2v 480p ────────────────────────────────────────────────
  'wavespeedai/wan-2.1-i2v-480p': {
    supportsImg2Img: true,
    supportsMultiImage: false,
    supportsSeed: true,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 1,
    resolutions: ['480p'],
    aspectRatios: [],
    pricePerImage: 0.04,
  },
  // ── 14. Wan 2.1 i2v 720p ────────────────────────────────────────────────
  'wavespeedai/wan-2.1-i2v-720p': {
    supportsImg2Img: true,
    supportsMultiImage: false,
    supportsSeed: true,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 1,
    resolutions: ['720p'],
    aspectRatios: [],
    pricePerImage: 0.08,
  },
  // ── Seedance 2.0 (video) ──────────────────────────────────────────────────
  'bytedance/seedance-2.0': {
    supportsImg2Img: true,
    supportsMultiImage: true, // supports up to 9 ref images + first/last frame
    supportsSeed: true,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 9,
    resolutions: ['480p', '720p', '1080p', '4k'],
    aspectRatios: ['16:9', '4:3', '1:1', '3:4', '9:16', '21:9', '9:21', 'adaptive'],
    pricePerImage: 0.08,
  },
  // ── Kling v3 Omni Video ──────────────────────────────────────────────────
  'kwaivgi/kling-v3-omni-video': {
    supportsImg2Img: true,
    supportsMultiImage: false,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 1,
    resolutions: ['standard', 'pro', '4k'],
    aspectRatios: ['adaptive', '16:9', '9:16', '1:1'],
    pricePerImage: 0.12,
  },
  // ── Grok Imagine Video 1.5 ──────────────────────────────────────────────────
  'xai/grok-imagine-video-1.5': {
    supportsImg2Img: true,
    supportsMultiImage: false,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 1,
    resolutions: ['720p', '480p'],
    aspectRatios: ['auto', '16:9', '4:3', '1:1', '9:16', '3:4', '3:2', '2:3'],
    pricePerImage: 0.10,
  },
  // ── Pruna AI P-Video ──────────────────────────────────────────────────
  'prunaai/p-video': {
    supportsImg2Img: true,
    supportsMultiImage: false,
    supportsSeed: true,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 1,
    resolutions: ['720p', '1080p'],
    aspectRatios: ['adaptive', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3', '1:1'],
    pricePerImage: 0.08,
  },
  // ── Google Veo 3.1 Fast ──────────────────────────────────────────────────
  'google/veo-3.1-fast': {
    supportsImg2Img: true,
    supportsMultiImage: false,
    supportsSeed: true,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 1,
    resolutions: ['720p', '1080p'],
    aspectRatios: ['adaptive', '16:9', '9:16'],
    pricePerImage: 0.15,
  },
  // ── PixVerse v6 ──────────────────────────────────────────────────
  'pixverse/pixverse-v6': {
    supportsImg2Img: true,
    supportsMultiImage: false,
    supportsSeed: true,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 1,
    resolutions: ['360p', '540p', '720p', '1080p'],
    aspectRatios: ['adaptive', '16:9', '9:16', '1:1'],
    pricePerImage: 0.09,
  },
  // ── OpenAI Sora 2 Pro ──────────────────────────────────────────────────
  'openai/sora-2-pro': {
    supportsImg2Img: true,
    supportsMultiImage: false,
    supportsSeed: true,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 1,
    resolutions: ['standard', 'high'],
    aspectRatios: ['adaptive', 'portrait', 'landscape'],
    pricePerImage: 0.20,
  },
  // ── 15. Tripo3D ───────────────────────────────────────────────────────────
  'zsxkib/tripo3d': {
    supportsImg2Img: true,
    supportsMultiImage: false,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 1,
    resolutions: [],
    aspectRatios: [],
    pricePerImage: 0.03,
  },
  // ── 16-18. Chat Models ──────────────────────────────────────────────────
  'meta/meta-llama-3-70b-instruct': {
    supportsImg2Img: false,
    supportsMultiImage: false,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 0,
    resolutions: [],
    aspectRatios: [],
    pricePerImage: 0,
  },
  'anthropic/claude-3.7-sonnet': {
    supportsImg2Img: false,
    supportsMultiImage: false,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 0,
    resolutions: [],
    aspectRatios: [],
    pricePerImage: 0,
  },
  'deepseek-ai/deepseek-r1': {
    supportsImg2Img: false,
    supportsMultiImage: false,
    supportsSeed: false,
    supportsSteps: false,
    supportsNegativePrompt: false,
    supportsUpscale: false,
    supportsLoRA: false,
    supportsReferenceStrength: false,
    defaultSteps: 1,
    stepsRange: [1, 1],
    maxReferenceImages: 0,
    resolutions: [],
    aspectRatios: [],
    pricePerImage: 0,
  },
};

// ── Helpers ───────────────────────────────────────────────────────────────────
export function arToSize(ar: string, base: number): { width: number; height: number } {
  const map: Record<string, { width: number; height: number }> = {
    '1:1': { width: base, height: base },
    '16:9': { width: base, height: Math.round(base * 9 / 16) },
    '9:16': { width: Math.round(base * 9 / 16), height: base },
    '4:3': { width: base, height: Math.round(base * 3 / 4) },
    '3:4': { width: Math.round(base * 3 / 4), height: base },
    '3:2': { width: base, height: Math.round(base * 2 / 3) },
    '2:3': { width: Math.round(base * 2 / 3), height: base },
  };
  return map[ar] ?? { width: base, height: base };
}

export function resolutionToPixels(res: string): number {
  if (!res || res === 'Auto') return 1024;
  const upper = res.toUpperCase();
  if (upper === '1K' || upper === 'HD' || upper === 'STANDARD') return 1024;
  if (upper === '2K' || upper === 'QHD') return 1536;
  if (upper === '4K' || upper === 'UHD') return 2048;
  const n = Number.parseInt(res, 10);
  return (isNaN(n) || n < 256) ? 1024 : n;
}


  export const MODEL_VERSIONS: Record<string, string> = {
    'philz1337x/clarity-upscaler': 'dfad41707589d68ecdccd1dfa600d55a208f9310748e44bfe35b4a6291453d5e',
    'philz1337x/clarity-pro-upscaler': '8e33eb474936d75d3ceaa787f3e66f5ba16f35db0853a7697a4ca4e5fc14b6cd',
  };
