export interface CometModelSpec {
  id: string; // The catalog ID used in UI: e.g. 'openai/gpt-6-1-sol'
  cometId: string; // The endpoint model ID: e.g. 'gpt-6.1-sol'
  fallbackIds?: string[];
  label: string;
  vendor: string;
  focus: string;
  badge?: string;
  inputCostPer1M: number; // in USD
  outputCostPer1M: number; // in USD
  creditsPer1MInput: number;
  creditsPer1MOutput: number;
  cacheReadCostPer1M?: number;
  cacheWriteCostPer1M?: number;
  creditsPer1MCacheRead?: number;
  creditsPer1MCacheWrite?: number;
  rank: number; // Cost efficiency rank (1 = most economical)
  longContextPricing?: {
    inputCostPer1M: number;
    outputCostPer1M: number;
    creditsPer1MInput: number;
    creditsPer1MOutput: number;
    cacheReadCostPer1M?: number;
    cacheWriteCostPer1M?: number;
    creditsPer1MCacheRead?: number;
    creditsPer1MCacheWrite?: number;
  };
}

export const COMET_MODELS: CometModelSpec[] = [
  {
    id: 'midjourney/mj-turbo-upscale',
    cometId: 'mj_turbo_upscale',
    label: 'Midjourney Turbo Upscale',
    vendor: 'Midjourney (CometAPI)',
    focus: 'Super-resolution AI upscaling via Midjourney Turbo engine',
    badge: 'MJ Turbo ⚡',
    inputCostPer1M: 0,
    outputCostPer1M: 0,
    creditsPer1MInput: 0,
    creditsPer1MOutput: 0,
    rank: 1,
  },
  {
    id: 'midjourney/mj-turbo-upscale-subtle',
    cometId: 'mj_turbo_upscale_subtle',
    label: 'Midjourney Turbo Upscale Subtle',
    vendor: 'Midjourney (CometAPI)',
    focus: 'Subtle high-resolution upscaling preserving original style, geometry & composition',
    badge: 'MJ Turbo Subtle ⚡',
    inputCostPer1M: 0,
    outputCostPer1M: 0,
    creditsPer1MInput: 0,
    creditsPer1MOutput: 0,
    rank: 1,
  },
  {
    id: 'midjourney/mj-turbo-upscale-creative',
    cometId: 'mj_turbo_upscale_creative',
    label: 'Midjourney Turbo Upscale Creative',
    vendor: 'Midjourney (CometAPI)',
    focus: 'High-creativity photorealistic super-resolution upscaling adding fine architectural textures',
    badge: 'MJ Turbo Creative ✨',
    inputCostPer1M: 0,
    outputCostPer1M: 0,
    creditsPer1MInput: 0,
    creditsPer1MOutput: 0,
    rank: 1,
  },
  {
    id: 'midjourney/mj-fast-upscale',
    cometId: 'mj_fast_upscale',
    label: 'Midjourney Fast Upscale',
    vendor: 'Midjourney (CometAPI)',
    focus: 'Fast standard upscale via Midjourney grid selector',
    badge: 'MJ Fast 🚀',
    inputCostPer1M: 0,
    outputCostPer1M: 0,
    creditsPer1MInput: 0,
    creditsPer1MOutput: 0,
    rank: 1,
  },
  {
    id: 'midjourney/mj-fast-upscale-subtle',
    cometId: 'mj_fast_upscale_subtle',
    label: 'Midjourney Fast Upscale Subtle',
    vendor: 'Midjourney (CometAPI)',
    focus: 'Subtle upscale preserving low-frequency details',
    badge: 'MJ Fast Subtle 🚀',
    inputCostPer1M: 0,
    outputCostPer1M: 0,
    creditsPer1MInput: 0,
    creditsPer1MOutput: 0,
    rank: 1,
  },
  {
    id: 'midjourney/mj-fast-upscale-creative',
    cometId: 'mj_fast_upscale_creative',
    label: 'Midjourney Fast Upscale Creative',
    vendor: 'Midjourney (CometAPI)',
    focus: 'Creative fast upscale synthesizing complex architectural patterns',
    badge: 'MJ Fast Creative 🎨',
    inputCostPer1M: 0,
    outputCostPer1M: 0,
    creditsPer1MInput: 0,
    creditsPer1MOutput: 0,
    rank: 1,
  },
  {
    id: 'openai/gpt-5-4',
    cometId: 'gpt-5.4',
    label: 'GPT-5.4',
    vendor: 'OpenAI (CometAPI)',
    focus: 'High-speed architectural analysis and rapid ideation: 25 credits in / 125 credits out',
    badge: '⚡ سريع واقتصادي (25–125 كريدت)',
    inputCostPer1M: 2.50,
    outputCostPer1M: 10.00,
    creditsPer1MInput: 25,
    creditsPer1MOutput: 125,
    cacheReadCostPer1M: 0.25,
    cacheWriteCostPer1M: 2.50,
    creditsPer1MCacheRead: 1,
    creditsPer1MCacheWrite: 25,
    rank: 1,
    longContextPricing: {
      inputCostPer1M: 5.00,
      outputCostPer1M: 15.00,
      creditsPer1MInput: 50,
      creditsPer1MOutput: 155,
      cacheReadCostPer1M: 0.50,
      cacheWriteCostPer1M: 5.00,
      creditsPer1MCacheRead: 5,
      creditsPer1MCacheWrite: 50,
    },
  },
  {
    id: 'openai/gpt-5-4-mini',
    cometId: 'gpt-5.4-mini',
    label: 'GPT-5.4 Mini',
    vendor: 'OpenAI (CometAPI)',
    focus: 'Ultra-fast, ultra-low-cost lightweight parser and prompt refiner: 5 credits in / 20 credits out',
    badge: '💨 خفيف وفائق السرعة (5–20 كريدت)',
    inputCostPer1M: 0.40,
    outputCostPer1M: 1.60,
    creditsPer1MInput: 5,
    creditsPer1MOutput: 20,
    cacheReadCostPer1M: 0.04,
    cacheWriteCostPer1M: 0.40,
    creditsPer1MCacheRead: 1,
    creditsPer1MCacheWrite: 5,
    rank: 1,
    longContextPricing: {
      inputCostPer1M: 0.80,
      outputCostPer1M: 3.20,
      creditsPer1MInput: 10,
      creditsPer1MOutput: 35,
      cacheReadCostPer1M: 0.08,
      cacheWriteCostPer1M: 0.80,
      creditsPer1MCacheRead: 1,
      creditsPer1MCacheWrite: 10,
    },
  },
  {
    id: 'openai/gpt-5-4-nano',
    cometId: 'gpt-5.4-nano',
    label: 'GPT-5.4 Nano',
    vendor: 'OpenAI (CometAPI)',
    focus: 'Micro-token intent classification and instant JSON extraction: 2 credits in / 8 credits out',
    badge: '🟢 فائق التوفير (2–8 كريدت)',
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.60,
    creditsPer1MInput: 2,
    creditsPer1MOutput: 8,
    cacheReadCostPer1M: 0.015,
    cacheWriteCostPer1M: 0.15,
    creditsPer1MCacheRead: 1,
    creditsPer1MCacheWrite: 2,
    rank: 1,
  },
  {
    id: 'openai/gpt-5-4-pro',
    cometId: 'gpt-5.4-pro',
    label: 'GPT-5.4 Pro',
    vendor: 'OpenAI (CometAPI)',
    focus: 'Deep multi-agent architectural reasoning, structural synthesis & BIM logic: 60 credits in / 280 credits out',
    badge: '💎 احترافي عالي الدقة (60–280 كريدت)',
    inputCostPer1M: 6.00,
    outputCostPer1M: 25.00,
    creditsPer1MInput: 60,
    creditsPer1MOutput: 280,
    cacheReadCostPer1M: 0.60,
    cacheWriteCostPer1M: 7.00,
    creditsPer1MCacheRead: 1,
    creditsPer1MCacheWrite: 75,
    rank: 2,
    longContextPricing: {
      inputCostPer1M: 12.00,
      outputCostPer1M: 40.00,
      creditsPer1MInput: 125,
      creditsPer1MOutput: 420,
      cacheReadCostPer1M: 1.20,
      cacheWriteCostPer1M: 14.00,
      creditsPer1MCacheRead: 15,
      creditsPer1MCacheWrite: 150,
    },
  },
  {
    id: 'openai/gpt-6-1-sol',
    cometId: 'gpt-6.1-sol',
    label: 'GPT-6.1 Sol',
    vendor: 'OpenAI (CometAPI)',
    focus: 'Solar radiation analysis, facade shading, thermal performance & daylight simulations: 50 credits in / 220 credits out',
    badge: '☀️ التحليل الشمسي والواجهات (50–220 كريدت)',
    inputCostPer1M: 5.00,
    outputCostPer1M: 20.00,
    creditsPer1MInput: 50,
    creditsPer1MOutput: 220,
    cacheReadCostPer1M: 0.50,
    cacheWriteCostPer1M: 5.00,
    creditsPer1MCacheRead: 1,
    creditsPer1MCacheWrite: 55,
    rank: 3,
    longContextPricing: {
      inputCostPer1M: 10.00,
      outputCostPer1M: 32.00,
      creditsPer1MInput: 105,
      creditsPer1MOutput: 335,
      cacheReadCostPer1M: 1.00,
      cacheWriteCostPer1M: 10.00,
      creditsPer1MCacheRead: 10,
      creditsPer1MCacheWrite: 110,
    },
  },
  {
    id: 'openai/gpt-6-astra',
    cometId: 'gpt-6-astra',
    label: 'GPT-6 Astra',
    vendor: 'OpenAI (CometAPI)',
    focus: 'Extreme-depth mathematical massing & frontier flagship reasoning: 85 credits in / 420 credits out',
    badge: '👑 عملاق الاستدلال (85–420 كريدت)',
    inputCostPer1M: 8.00,
    outputCostPer1M: 40.00,
    creditsPer1MInput: 85,
    creditsPer1MOutput: 420,
    cacheReadCostPer1M: 0.80,
    cacheWriteCostPer1M: 10.00,
    creditsPer1MCacheRead: 1,
    creditsPer1MCacheWrite: 110,
    rank: 4,
    longContextPricing: {
      inputCostPer1M: 16.00,
      outputCostPer1M: 60.00,
      creditsPer1MInput: 170,
      creditsPer1MOutput: 620,
      cacheReadCostPer1M: 1.60,
      cacheWriteCostPer1M: 20.00,
      creditsPer1MCacheRead: 20,
      creditsPer1MCacheWrite: 220,
    },
  },
  {
    id: 'xai/grok-4-1-fast-reasoning',
    cometId: 'grok-4-1-fast-reasoning',
    label: 'Grok 4.1 Fast Reasoning',
    vendor: 'xAI (CometAPI)',
    focus: 'Ultra-low latency architectural reasoning, instant script synthesis & spatial logic',
    badge: '⚡ فائق السرعة (~1.8 ثانية)',
    inputCostPer1M: 1.50,
    outputCostPer1M: 6.00,
    creditsPer1MInput: 15,
    creditsPer1MOutput: 60,
    rank: 1,
  },
  {
    id: 'google/gemini-3.8-flash-thinking',
    cometId: 'gemini-3.8-flash-thinking',
    label: 'Gemini 3.8 Flash Thinking',
    vendor: 'Google DeepMind (CometAPI)',
    focus: 'Fast multimodal spatial reasoning, visual facade parsing & rapid BIM synthesis',
    badge: '⚡ استجابة فورية (~1.5 ثانية)',
    inputCostPer1M: 1.20,
    outputCostPer1M: 4.80,
    creditsPer1MInput: 12,
    creditsPer1MOutput: 48,
    rank: 1,
  },
  {
    id: 'minimax/minimax-m3-1-flash-preview',
    cometId: 'minimax-m3.1-flash-preview',
    label: 'MiniMax M3.1 Flash',
    vendor: 'MiniMax (CometAPI)',
    focus: 'الأعلى توفيراً والأسرع للمسودات: 4–15 كريدت / مليون توكن (~2 ثانية)',
    badge: '⚡ فائق التوفير (4–15 كريدت)',
    inputCostPer1M: 0.40,
    outputCostPer1M: 1.50,
    creditsPer1MInput: 4,
    creditsPer1MOutput: 15,
    rank: 1,
  },
  {
    id: 'anthropic/claude-sonnet-5-5',
    cometId: 'claude-sonnet-5-5',
    label: 'Claude Sonnet 5.5',
    vendor: 'Anthropic (CometAPI)',
    focus: 'التوازن الذهبي للكتل الراقية: 20–85 كريدت / مليون توكن (~3.5 ثانية)',
    badge: '🏛️ الأفضل معمارياً (20–85 كريدت)',
    inputCostPer1M: 2.00,
    outputCostPer1M: 8.50,
    creditsPer1MInput: 20,
    creditsPer1MOutput: 85,
    rank: 2,
  },
  {
    id: 'google/gemini-4-argon',
    cometId: 'gemini-4-argon',
    label: 'Gemini 4 Argon',
    vendor: 'Google DeepMind (CometAPI)',
    focus: 'تحليل بصري متعدد الوسائط للواجهات والـ BIM: 36–170 كريدت / مليون توكن',
    badge: '👁️ رؤية معمارية (36–170 كريدت)',
    inputCostPer1M: 3.60,
    outputCostPer1M: 17.00,
    creditsPer1MInput: 36,
    creditsPer1MOutput: 170,
    rank: 3,
  },
  {
    id: 'anthropic/claude-fable-5-1',
    cometId: 'claude-table-5-1',
    label: 'Claude Fable 5.1',
    vendor: 'Anthropic (CometAPI)',
    focus: 'فلسفة معمارية وكتل عضوية طليعية: 85–420 كريدت / مليون توكن',
    badge: '🎨 فكر طليعي (85–420 كريدت)',
    inputCostPer1M: 8.50,
    outputCostPer1M: 42.00,
    creditsPer1MInput: 85,
    creditsPer1MOutput: 420,
    rank: 4,
  },
  {
    id: 'xai/grok-5',
    cometId: 'grok-4.7',
    label: 'Grok 5 / Grok 4.7',
    vendor: 'xAI (CometAPI)',
    focus: 'Analytical structural mechanics, real-time code generation & raw compute logic',
    badge: 'Advanced Logic 🚀',
    inputCostPer1M: 2.50,
    outputCostPer1M: 10.00,
    creditsPer1MInput: 25,
    creditsPer1MOutput: 100,
    rank: 2,
  },
];
